// Mocks generated by Mockito 5.3.2 from annotations
// in ottaa_project_flutter/test/providers/ChatGPT/chatgpt_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:either_dart/either.dart' as _i4;
import 'package:flutter_riverpod/flutter_riverpod.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:ottaa_project_flutter/application/notifiers/patient_notifier.dart'
    as _i5;
import 'package:ottaa_project_flutter/application/notifiers/user_notifier.dart'
    as _i9;
import 'package:ottaa_project_flutter/core/abstracts/user_model.dart' as _i3;
import 'package:ottaa_project_flutter/core/models/patient_user_model.dart'
    as _i2;
import 'package:ottaa_project_flutter/core/repositories/chatgpt_repository.dart'
    as _i10;
import 'package:state_notifier/state_notifier.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePatientUserModel_0 extends _i1.SmartFake
    implements _i2.PatientUserModel {
  _FakePatientUserModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserModel_1 extends _i1.SmartFake implements _i3.UserModel {
  _FakeUserModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_2<L, R> extends _i1.SmartFake implements _i4.Either<L, R> {
  _FakeEither_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PatientNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockPatientNotifier extends _i1.Mock implements _i5.PatientNotifier {
  @override
  _i2.PatientUserModel get user => (super.noSuchMethod(
        Invocation.getter(#user),
        returnValue: _FakePatientUserModel_0(
          this,
          Invocation.getter(#user),
        ),
        returnValueForMissingStub: _FakePatientUserModel_0(
          this,
          Invocation.getter(#user),
        ),
      ) as _i2.PatientUserModel);
  @override
  set onError(_i6.ErrorListener? _onError) => super.noSuchMethod(
        Invocation.setter(
          #onError,
          _onError,
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  _i7.Stream<_i2.PatientUserModel?> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i7.Stream<_i2.PatientUserModel?>.empty(),
        returnValueForMissingStub: _i7.Stream<_i2.PatientUserModel?>.empty(),
      ) as _i7.Stream<_i2.PatientUserModel?>);
  @override
  set state(_i2.PatientUserModel? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  void setUser(_i2.PatientUserModel? user) => super.noSuchMethod(
        Invocation.method(
          #setUser,
          [user],
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool updateShouldNotify(
    _i2.PatientUserModel? old,
    _i2.PatientUserModel? current,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            old,
            current,
          ],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  _i6.RemoveListener addListener(
    _i8.Listener<_i2.PatientUserModel?>? listener, {
    bool? fireImmediately = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
          {#fireImmediately: fireImmediately},
        ),
        returnValue: () {},
        returnValueForMissingStub: () {},
      ) as _i6.RemoveListener);
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [UserNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserNotifier extends _i1.Mock implements _i9.UserNotifier {
  @override
  _i3.UserModel get user => (super.noSuchMethod(
        Invocation.getter(#user),
        returnValue: _FakeUserModel_1(
          this,
          Invocation.getter(#user),
        ),
        returnValueForMissingStub: _FakeUserModel_1(
          this,
          Invocation.getter(#user),
        ),
      ) as _i3.UserModel);
  @override
  set onError(_i6.ErrorListener? _onError) => super.noSuchMethod(
        Invocation.setter(
          #onError,
          _onError,
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  _i7.Stream<_i3.UserModel?> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i7.Stream<_i3.UserModel?>.empty(),
        returnValueForMissingStub: _i7.Stream<_i3.UserModel?>.empty(),
      ) as _i7.Stream<_i3.UserModel?>);
  @override
  set state(_i3.UserModel? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  void setUser(_i3.UserModel? user) => super.noSuchMethod(
        Invocation.method(
          #setUser,
          [user],
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool updateShouldNotify(
    _i3.UserModel? old,
    _i3.UserModel? current,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            old,
            current,
          ],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  _i6.RemoveListener addListener(
    _i8.Listener<_i3.UserModel?>? listener, {
    bool? fireImmediately = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
          {#fireImmediately: fireImmediately},
        ),
        returnValue: () {},
        returnValueForMissingStub: () {},
      ) as _i6.RemoveListener);
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ChatGPTRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatGPTRepository extends _i1.Mock implements _i10.ChatGPTRepository {
  @override
  _i7.Future<_i4.Either<String, String>> getCompletion({
    required int? age,
    required String? gender,
    required String? pictograms,
    required String? language,
    int? maxTokens = 500,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCompletion,
          [],
          {
            #age: age,
            #gender: gender,
            #pictograms: pictograms,
            #language: language,
            #maxTokens: maxTokens,
          },
        ),
        returnValue: _i7.Future<_i4.Either<String, String>>.value(
            _FakeEither_2<String, String>(
          this,
          Invocation.method(
            #getCompletion,
            [],
            {
              #age: age,
              #gender: gender,
              #pictograms: pictograms,
              #language: language,
              #maxTokens: maxTokens,
            },
          ),
        )),
        returnValueForMissingStub: _i7.Future<_i4.Either<String, String>>.value(
            _FakeEither_2<String, String>(
          this,
          Invocation.method(
            #getCompletion,
            [],
            {
              #age: age,
              #gender: gender,
              #pictograms: pictograms,
              #language: language,
              #maxTokens: maxTokens,
            },
          ),
        )),
      ) as _i7.Future<_i4.Either<String, String>>);
}
